"""Add LibraryHistoricalStats model

Revision ID: 22e2f1ba82a6
Revises: f9fa12ab19f1
Create Date: 2025-10-01 16:38:38.547201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22e2f1ba82a6'
down_revision: Union[str, None] = 'f9fa12ab19f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('library_historical_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('library_id', sa.Integer(), nullable=False),
    sa.Column('library_name', sa.String(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('total_views', sa.Integer(), nullable=True),
    sa.Column('total_watch_time_seconds', sa.Integer(), nullable=True),
    sa.Column('bandwidth_gb', sa.Float(), nullable=True),
    sa.Column('views_chart', sa.JSON(), nullable=True),
    sa.Column('watch_time_chart', sa.JSON(), nullable=True),
    sa.Column('bandwidth_chart', sa.JSON(), nullable=True),
    sa.Column('fetch_date', sa.DateTime(), nullable=True),
    sa.Column('is_synced', sa.Boolean(), nullable=True),
    sa.Column('sync_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_index(op.f('ix_library_historical_stats_id'), 'library_historical_stats', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_library_historical_stats_id'), table_name='library_historical_stats')
    op.drop_table('library_historical_stats')
    # ### end Alembic commands ###
