"""Add total_watch_time_seconds to monthly_stats

Revision ID: f9fa12ab19f1
Revises: 9a5a41f83115
Create Date: 2025-09-30 23:16:14.928163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9fa12ab19f1'
down_revision: Union[str, None] = '9a5a41f83115'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monthly_stats', sa.Column('total_watch_time_seconds', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monthly_stats', 'total_watch_time_seconds')
    # ### end Alembic commands ###
